<div align="left">
<p><img alt="Sapiencia" height="140px" src="https://ubicua.ingeniaudea.co/pluginfile.php/32974/coursecat/description/RF_RedesNeuronales.png" align="left" hspace="10px" vspace="0px"></p></div>
<div align="left"></div>
<div>

<br></br>

<div align="left">
<br></br>
<br></br>



<hr size=10 noshade color="#663398">
</p>
<p>
<img alt="CC" height="70px" src="https://creativecommons.org/images/deed/cc_blue_x2.png" align="left" hspace="0px" vspace="0px">
<img alt="Attribution" height="70px" src="https://creativecommons.org/images/deed/attribution_icon_blue_x2.png" align="left" hspace="0px" vspace="0px">
<img alt="NC" height="70px" src="https://creativecommons.org/images/deed/nc_blue_x2.png" align="left" hspace="0px" vspace="0px">
<img alt="SA" height="70px" src="https://creativecommons.org/images/deed/sa_blue_x2.png" align="left" hspace="0px" vspace="0px">
</p>

<div align="right">
<h1> <b> Por: Cristiam Loaiza </b> </h1>
<h2> Ingeniero de datos </h2>
<a href="mailto:cristiam.loaiza@udea.edu.co"> ✉ Cristiam Loaiza</a>
</div>

<br>

**El presente material hace parte de la ruta de formación del talento especializado de SAPIENCIA**

**Los documentos que utilizaremos en la presente y proximas clases son una mezcla del trabajo de muchos profesores y académicos.**

**En caso de utilizar el presente contenido favor citarlo y brindar los créditos respectivos.**


In [2]:
import numpy as np

<p><a name="contents"></a></p>

# Contenido

- <a href="#Perceptron">1. Perceptron</a><br>
&nbsp;&nbsp; - [1.1 Tipo de Perceptrón](#Perceptron)<br>
&nbsp;&nbsp; - [1.2 Analogia](#Analogia)<br>



<p><a name="Perceptron"></a></p>

# 1) Perceptron

[[Contenidos]](#contents)


Un Perceptrón es básicamente un modelo de clasificacion lineal, donde usa como función de activación la función de heaviside, la cual recordemos tiene la siguiente forma:

 $heaviside(x)=\begin{cases} 
      0 & x < 0 \\
      1 & x\geq 0 
   \end{cases} $


Donde el perceptrón es considerado un algoritmo supervisado, cuyos pesos son los $w_{i}$ y el termino $b$ (bias) que podemos ver en las imagenes. 

<div style="text-align: center;">
    <img src="https://i.imgur.com/vNWd4os.png" height="300px"/>
</div>


Cuando ingresamos nuestros datos, este realiza una suma pesada definda como:

$z=\sum_{i=1}^{m}x_{i}w_{i}+b$

Es decir, cada entrada es multiplicada por un peso(el cual normalmente se inicia de forma aleatoria) y los resultados son sumados junto al b.

<p><img alt="Colaboratory logo" height="300px" src="https://s3.amazonaws.com/stackabuse/media/intro-to-neural-networks-scikit-learn-3.png" align="center" hspace="10px" vspace="0px"></p>

El perceptrón multicapa a diferencia del perceptrón trabaja bien en los casos donde tenemos datos separables no lineales. En las redes neuronales tenemos una capa de entrada, otra de salida y una o multiples capaz ocultas. Como se puede ver las conexiones siempre están dirigidas hacia adelante es decir, las neuronas de una capa se conectan con las neuronas de la siguiente capa.

Los pesos dentro de nuestra red neuronal típicamente están expresados como $w_{ij}^{[l]}$, donde "$l$" hace referencia a nuestra capa. De forma matricial podemos expresar los valores para la capa $l$ como:

\begin{equation}
Z^{[l]}=X^{[l-1]}W^{[l]}+B^{[l]}
\end{equation}

Donde $X$ es la matriz de tamaño $m\times n^{[l-1]}$, $W^{[l]}$ de $n^{[l-1]}\times n^{[l]}$ y $B$ de $1\times n^{[l]}$. Donde de nuevo $n^{[l]}$ hace referencia al número de neuronas en la capa $l$.  Donde tenemos que $X^{[l]}$ viene dada por 

\begin{equation}
X^{[l]}=f^{[l]}(Z^{[l]})
\end{equation}

Con $f^{[l]}$ la función de activación de la capa $l$.


<p><a name="redesIntro"></a></p>

# 2) Ejemplo red NNS (Perceptron) usando numpy

[[Contenidos]](#contents)

In [445]:
import numpy as np

In [451]:
###Entradas
X = np.array([[0,0],[0,1],[1,0],[1,1]])
#Salidas esperadas
Y = np.array([0,0,0,1])

w = np.random.rand(2)
b=  np.random.rand(1)


lr = 0.1
epoch = 100

for i in range(epoch):
    print(f"Epoch: {i+1} - {epoch}")
    y_h = np.dot(X,w) + b
    print(y_h)
    error = Y - y_h

    w = w + lr * np.dot(error,X)

    print(f"pesos= {w}")
    print(f"error= {error}")
    b = b + lr*error

    print(f"Sesgo : {b}")

Epoch: 1 - 100
[0.28684901 0.49686187 1.22764023 1.43765309]
pesos= [0.77426189 0.11656137]
error= [-0.28684901 -0.49686187 -1.22764023 -0.43765309]
Sesgo : [0.25816411 0.23716282 0.16408498 0.2430837 ]
Epoch: 2 - 100
[0.25816411 0.35372419 0.93834687 1.13390695]
pesos= [0.66703651 0.06779825]
error= [-0.25816411 -0.35372419 -0.93834687 -0.13390695]
Sesgo : [0.23234769 0.2017904  0.0702503  0.229693  ]
Epoch: 3 - 100
[0.23234769 0.26958865 0.7372868  0.96452776]
pesos= [0.59685505 0.04438661]
error= [-0.23234769 -0.26958865 -0.7372868   0.03547224]
Sesgo : [ 0.20911293  0.17483153 -0.00347838  0.23324023]
Epoch: 4 - 100
[0.20911293 0.21921815 0.59337667 0.87448189]
pesos= [0.5500692  0.03501661]
error= [-0.20911293 -0.21921815 -0.59337667  0.12551811]
Sesgo : [ 0.18820163  0.15290972 -0.06281605  0.24579204]
Epoch: 5 - 100
[0.18820163 0.18792633 0.48725314 0.83087784]
pesos= [0.5182561  0.03313619]
error= [-0.18820163 -0.18792633 -0.48725314  0.16912216]
Sesgo : [ 0.16938147  0.1341170

In [453]:
print(b)

[ 7.61911086e-06 -6.77200245e-02 -4.33109204e-01  4.99136591e-01]


In [454]:
w

array([0.4331206 , 0.06773142])

In [455]:
X

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [452]:


prediccion = np.dot(X,w) + b

print(prediccion)

[7.61911086e-06 1.13934288e-05 1.13935777e-05 9.99988606e-01]


<p><a name="Perceptron"></a></p>

### 1.1. Tipos de perceptrones

* Perceptrón de una sola capa
* Perceptrón multicapa

<p><a name="Analogia"></a></p>

## 2. Descenso del grandiente

Función de perdida

La función de perdida mide que tan lejos se encuentran nuestras predicciones de los valores a los que tenemos que llegar. 
Para el siguiente ejemplo usaremos una función muy común que es la función de error cuadratico medio.


$L(w,b) = \frac{1}{N}\sum\limits_{i=0}^{N-1}(y_{pred}^{(i)} - y_{target}^{(i)})^2$

donde N es el número de muestras, $y_{pred}^{(i)}$ es el valor de la predicción y  $y_{target}^{(i)}$ es el valor de referencia.

**Gradiente**
Usando la regla de la cadena en derivadas. El resultado de las derivadas parciales para la función de pesos y sesgos es:

$\frac{\partial L}{\partial w_{jk}} = \frac{1}{N}\sum\limits_{i=0}^{N-1} (y_{pred}^{(i)} - y_{target}^{(i)}) \frac{\partial y_{pred}^{(i)}}{\partial w_{jk}}$

$\frac{\partial L}{\partial b_{j}} = \frac{1}{N}\sum\limits_{i=0}^{N-1} (y_{pred}^{(i)} - y_{target}^{(i)}) \frac{\partial y_{pred}^{(i)}}{\partial b_{j}}$

donde  $w_{jk}$ es el peso del nodo de  k a j y $b_{j}$ es el sesgo del nodo j.


**Actualizar pesos**


$w_{jk} := w_{jk} - \alpha \frac{\partial L}{\partial w_{jk}}$

$b_{j} := b_{j} - \alpha \frac{\partial L}{\partial b_{j}}$

Donde α is the tasa de aprendizaje. Esta actualiza los pesos/sesgos en una dirección negativa del gradiente para minimizar los valores de perdida.

En resumen, calculamos la función de pérdida, las derivadas de la función de pérdida para obtener los gradientes y actualizamos los parámetros utilizando los gradientes. Este proceso se aplica a todos los pesos y sesgos de la red.

#### Generalidades



El producto punto entre dos vectores 
$ \mathbf{a}$ y $\mathbf{b}$ se denota como $\mathbf{a} \cdot \mathbf{b} $

 y se calcula mediante la siguiente fórmula:

$
\mathbf{a} \cdot \mathbf{b} = \sum_{i=1}^{n} a_i b_i
$




---

In [32]:
weights = np.array([0.5,0.48,-0.7])



streetlights = np.array([
    [1,0,1],
    [0,1,1],
    [0,0,1],
    [1,1,1],
    [0,1,1],
    [1,0,1]

])


walk_vs_stop = np.array([0,1,0,1,1,0]) # cuando es cero no puede caminar

input = streetlights[0]
goal_prediction = walk_vs_stop[0]


print(f"primera entrada {input} la prediccion es: {goal_prediction}")

epoch = 5
lr= 0.1

for i in range(epoch):
    print(f"epoca numero {i}")
    error_for_all_weigths = 0
    for r_index in range(len(walk_vs_stop)):
        input = streetlights[r_index]
        #         goal prediction
        goal_prediction = walk_vs_stop[r_index]
        prediction = input.dot(weights)
        #prediction = np.dot(input,weights)
        error = (goal_prediction - prediction)**2 
        error_for_all_weigths = error_for_all_weigths + error

        delta = prediction - goal_prediction

        weights = weights - lr*(input*delta)
        print(f"prediccion: {prediction}")
    print("error para todos los pesos", error_for_all_weigths )

    #print(f"parametro de entrada: {input} meta de prediccion {goal_prediction} error para todos los pesos {error_for_all_weigths}")
    




primera entrada [1 0 1] la prediccion es: 0
epoca numero 0
prediccion: -0.19999999999999996
prediccion: -0.19999999999999996
prediccion: -0.5599999999999999
prediccion: 0.6160000000000001
prediccion: 0.17279999999999995
prediccion: 0.17552
error para todos los pesos 2.6561231104
epoca numero 1
prediccion: 0.14041599999999999
prediccion: 0.3066464
prediccion: -0.34513824
prediccion: 1.006637344
prediccion: 0.4785034751999999
prediccion: 0.26700416768
error para todos los pesos 0.9628701776715985
epoca numero 2
prediccion: 0.213603334144
prediccion: 0.5347420299776
prediccion: -0.26067345110016
prediccion: 1.1319428845096962
prediccion: 0.6274723921901568
prediccion: 0.25433999330650114
error para todos los pesos 0.5509165866836797
epoca numero 3
prediccion: 0.20347199464520088
prediccion: 0.6561967149569552
prediccion: -0.221948503950995
prediccion: 1.166258650532124
prediccion: 0.7139004922542389
prediccion: 0.21471099528371604
error para todos los pesos 0.36445836852222424
epoca numer

## 2. Backpropagation

 La técnica de backpropagation ajusta los pesos y sesgos para minimizar la diferencia entre las salidas y las entradas.

 El algoritmo utiliza una técnica de optimización matemática llamada gradiente descendente, que permite ajustar los pesos y sesgos de la red para minimizar el error. El proceso de ajuste se realiza en dos fases: en la propagación hacia adelante (forward propagation), se calcula la salida de la red para una entrada dada, y en la propagación hacia atrás (back propagation) se ajustan los pesos y sesgos de la red para minimizar el error.
<br>

**Propagación hacia adelante:**  En esta fase, se introducen los datos de entrada en la red neuronal y se propagan a través de las capas ocultas hasta la capa de salida. En esta capa, se calcula la salida de la red.<br>
**Propagación hacia atrás:** En esta fase, se calcula el error entre la salida de la red y la salida deseada. Luego, se propaga este error hacia atrás a través de la red neuronal, desde la capa de salida hacia las capas ocultas. Durante la propagación hacia atrás, se calcula la derivada parcial del error con respecto a cada peso y sesgo de la red.<br>
A partir de estas derivadas parciales, se actualizan los pesos y sesgos de la red utilizando la técnica de gradiente descendente. La idea detrás del gradiente descendente es ajustar los pesos y sesgos de la red de manera que minimicen el error en cada época de entrenamiento. El algoritmo utiliza la derivada del error con respecto a cada peso y sesgo para determinar la dirección y magnitud del ajuste.

---

Este código implementa un ejemplo simple de entrenamiento de una red neuronal mediante el algoritmo de retropropagación (backpropagation). El objetivo de esta red neuronal es predecir si una persona debería caminar o detenerse en función de las señales del semáforo en una intersección.

Aquí tienes un desglose paso a paso del código junto con las fórmulas matemáticas involucradas:

Importar bibliotecas y configurar semilla aleatoria:

In [37]:
import numpy as np

np.random.seed(1)

Se importa la biblioteca NumPy para realizar cálculos numéricos y se establece una semilla aleatoria para reproducibilidad.

Definir funciones de activación:

In [14]:
def relu(x):
    return (x > 0) * x

def relu2deriv(output):
    return output > 0

Se definen dos funciones: relu, que implementa la función de activación ReLU (Rectified Linear Unit), y relu2deriv, que devuelve la derivada de ReLU respecto a su entrada.

Configurar parámetros de la red neuronal:

In [15]:
alpha = 0.2
hidden_size = 4

alpha es la tasa de aprendizaje que controla el tamaño de los pasos en la actualización de los pesos durante el entrenamiento. hidden_size es el número de neuronas en la capa oculta de la red.

Inicializar pesos aleatorios:

In [16]:
weights_0_1 = 2 * np.random.random((3, hidden_size)) - 1
weights_1_2 = 2 * np.random.random((hidden_size, 1)) - 1

Se inicializan aleatoriamente los pesos de las conexiones entre la capa de entrada y la capa oculta (weights_0_1) y entre la capa oculta y la capa de salida (weights_1_2).

Definir los datos de entrada y las etiquetas de salida:

In [17]:
streetlights = np.array([[1, 0, 1],
                         [0, 1, 1],
                         [0, 0, 1],
                         [1, 1, 1]])

walk_vs_stop = np.array([[1, 1, 0, 0]]).T


streetlights representa las señales del semáforo para cada intersección, donde cada fila es una instancia y cada columna corresponde a una señal. walk_vs_stop son las etiquetas de salida correspondientes, donde 1 representa "caminar" y 0 representa "detenerse".

Ciclo de entrenamiento:

In [18]:
for iteration in range(60):
    layer_2_error = 0
    for i in range(len(streetlights)):
        layer_0 = streetlights[i:i+1]
        layer_1 = relu(np.dot(layer_0, weights_0_1))
        layer_2 = np.dot(layer_1, weights_1_2)

        layer_2_error += np.sum((layer_2 - walk_vs_stop[i:i+1]) ** 2)

        layer_2_delta = (walk_vs_stop[i:i+1] - layer_2)
        layer_1_delta = layer_2_delta.dot(weights_1_2.T) * relu2deriv(layer_1)

        weights_1_2 += alpha * layer_1.T.dot(layer_2_delta)
        weights_0_1 += alpha * layer_0.T.dot(layer_1_delta)

    if iteration % 10 == 9:
        print("Error:" + str(layer_2_error))


Error:0.6342311598444467
Error:0.35838407676317513
Error:0.0830183113303298
Error:0.006467054957103705
Error:0.0003292669000750734
Error:1.5055622665134859e-05


Este ciclo es el núcleo del entrenamiento de la red neuronal. Aquí está lo que sucede en cada iteración:

Se calcula la salida de la capa oculta (layer_1) aplicando la función ReLU a la entrada ponderada (np.dot(layer_0, weights_0_1)).
Se calcula la salida de la capa de salida (layer_2) como el producto escalar entre layer_1 y weights_1_2.
Se calcula el error acumulado en esta iteración sumando el cuadrado de las diferencias entre las salidas predichas (layer_2) y las etiquetas reales (walk_vs_stop).<br>
Se calcula layer_2_delta, que es la diferencia entre las salidas reales y las predichas en la capa de salida.
Se calcula layer_1_delta, que es el producto del delta de la capa de salida y los pesos weights_1_2 transpuestos, multiplicado por la derivada de la función de activación ReLU aplicada a layer_1.<br>
Se actualizan los pesos de weights_1_2 y weights_0_1 utilizando el algoritmo de descenso de gradiente (gradiente descendente) multiplicado por la tasa de aprendizaje (alpha).<br>
Cada 10 iteraciones, se imprime el error acumulado en la capa de salida.<br>
El código entrena una red neuronal de dos capas (una capa oculta y una capa de salida) para predecir si una persona debería caminar o detenerse en función de las señales del semáforo en una intersección. Utiliza la función de activación ReLU y el algoritmo de retropropagación para ajustar los pesos de la red en cada iteración, minimizando así el error entre las predicciones y las etiquetas reales.<br>

In [3]:
import numpy as np

np.random.seed(1)

def relu(x):
    return (x > 0) * x # returns x if x > 0
                       # return 0 otherwise

def relu2deriv(output):
    return output>0 # returns 1 for input > 0
                    # return 0 otherwise



alpha = 0.2
hidden_size = 4

weights_0_1 = 2*np.random.random((3,hidden_size)) - 1
weights_1_2 = 2*np.random.random((hidden_size,1)) - 1


streetlights = np.array( [[ 1, 0, 1 ],
                          [ 0, 1, 1 ],
                          [ 0, 0, 1 ],
                          [ 1, 1, 1 ] ] )

walk_vs_stop = np.array([[ 1, 1, 0, 0]]).T




for iteration in range(60):
   layer_2_error = 0
   for i in range(len(streetlights)):
      layer_0 = streetlights[i:i+1]
      layer_1 = relu(np.dot(layer_0,weights_0_1))
      layer_2 = np.dot(layer_1,weights_1_2)

      layer_2_error += np.sum((layer_2 - walk_vs_stop[i:i+1]) ** 2)

      layer_2_delta = (walk_vs_stop[i:i+1] - layer_2)
      layer_1_delta=layer_2_delta.dot(weights_1_2.T)*relu2deriv(layer_1)

      weights_1_2 += alpha * layer_1.T.dot(layer_2_delta)
      weights_0_1 += alpha * layer_0.T.dot(layer_1_delta)

   if(iteration % 10 == 9):
      print("Error:" + str(layer_2_error))

Error:0.6342311598444467
Error:0.35838407676317513
Error:0.0830183113303298
Error:0.006467054957103705
Error:0.0003292669000750734
Error:1.5055622665134859e-05


$\text{Layer 0 (Input Layer): } \mathbf{layer\_0} = \text{streetlights}[i:i+1]$

$\text{Layer 1 (Hidden Layer): } \mathbf{layer\_1} = \text{ReLU}(\mathbf{layer\_0} \cdot \mathbf{weights\_0\_1})$

$\text{Layer 2 (Output Layer): } \mathbf{layer\_2} = \mathbf{layer\_1} \cdot \mathbf{weights\_1\_2}$


$\text{Layer 2 Error: } \mathbf{layer\_2\_error} += \sum_{j} (\mathbf{layer\_2}[j] - \text{walk\_vs\_stop}[i:i+1][j])^2$


#### Next

# Redes Neuronales Recurrentes

# Redes Convolucionales